@startuml
package Dao {
    package impl {
        class ConfiguracionJDBC{
                - String jdbcDriver
                - String dbUrl
                - String nombreUsuario
                - String contrasenia
                --
                + ConfiguracionJDBC(String jdbcDriver, String dbUrl, String nombreUsuario, String contrasenia)
                + contectarConBD()
        }
        class GeneradorDeSentenciasMedicamentos{
                + generarInsert
        }
    }
}

@enduml