use dhtube;
select * from usuario where nombre like 'a%';
select * from usuario where email is null or email = '';
select * from canal where fechaCreacion between '2021-04-01' and '2021-06-01';
select * from usuario order by fechaNacimiento asc limit 10;
select * from playlist where privado = 1;
select * from video order by cantidadLikes limit 5;
insert into usuario values (20, 'Juan Jose Batzal', 'jjbatzal@gmail.com', 'jj1597', '2000-04-01', '1429', 9, 85);
select * from usuario where fechaNacimiento like '2000%';
select upper(nombre) from pais order by nombre;
select * from video where cantidadReproducciones >= 500000;
select * from video where fechaPublicacion like '2020%' and privado = 1 and cantidadDislikes > 100;
update usuario set  fechaNacimiento = '2000-01-04' where nombre = 'Juan Jose Batzal';
select * from usuario where LENGTH(password) < 5;
select idUsuario as 'ID', nombre as 'Nombre', email as 'E-mail', fechaNacimiento as 'Fecha de Nacimiento',FLOOR(DATEDIFF(CURRENT_DATE(),fechaNacimiento)/365) as 'Edad', codigoPostal as 'Codigo de País' from usuario;
select * from video order by duracion desc limit 1;
select fecha, TipoReaccion_idTipoReaccion, Usuario_idUsuario, Video_idVideo from reaccion order by fecha desc limit 10;
select * from video where cantidadReproducciones < 100000 and cantidadLikes >= 100;
select * from video where descripcion like '%FAN%';
select * from usuario where password in ('123','1234','12345','abc','clave','password');
delete from avatar where nombre = 'avDhTube';
