-- MySQL Script generated by MySQL Workbench
-- Sat Aug 28 00:07:35 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Spotify
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Spotify
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Spotify` DEFAULT CHARACTER SET utf8 ;
USE `Spotify` ;

-- -----------------------------------------------------
-- Table `Spotify`.`GENDER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`GENDER` (
  `gender_id` INT NOT NULL AUTO_INCREMENT,
  `gender_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`gender_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`USER` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `user_password` VARCHAR(32) NOT NULL,
  `user_password_creation_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user_password_exp_date` DATE NOT NULL,
  `user_birthday` DATE NOT NULL,
  `user_gender_id` INT NOT NULL,
  `user_zipcode` VARCHAR(45) NOT NULL,
  `user_country` VARCHAR(45) NOT NULL,
  `user_membership_status` TINYINT NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `user_gender_id_idx` (`user_gender_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_gender_id`
    FOREIGN KEY (`user_gender_id`)
    REFERENCES `Spotify`.`GENDER` (`gender_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Spotify`.`PLAYLISTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`PLAYLISTS` (
  `playlist_id` INT NOT NULL,
  `playlist_title` VARCHAR(45) NOT NULL,
  `playlist_user_id` INT NOT NULL,
  `playlist_creation_date` DATE NOT NULL,
  `playlist_deletion_date` DATE NULL,
  PRIMARY KEY (`playlist_id`),
  INDEX `playlist_user_id_idx` (`playlist_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_playlist_user_id`
    FOREIGN KEY (`playlist_user_id`)
    REFERENCES `Spotify`.`USER` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`ARTIST`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`ARTIST` (
  `artist_id` INT NOT NULL,
  `artist_name` VARCHAR(45) NOT NULL,
  `artist_img_url` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`artist_id`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `Spotify`.`RECORD_COMPANY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`RECORD_COMPANY` (
  `record_company_id` INT NOT NULL,
  `record_company_name` VARCHAR(45) NOT NULL,
  `record_company_country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`record_company_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`ALBUM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`ALBUM` (
  `album_id` INT NOT NULL,
  `album_title` VARCHAR(45) NOT NULL,
  `album_release` DATE NOT NULL,
  `album_record_company_id` INT NOT NULL,
  `album_img_url` VARCHAR(45) NOT NULL,
  `album_artist_id` INT NOT NULL,
  PRIMARY KEY (`album_id`),
  INDEX `album_artist_id_idx` (`album_artist_id` ASC) VISIBLE,
  INDEX `album_record_company_id_idx` (`album_record_company_id` ASC) VISIBLE,
  CONSTRAINT `album_artist_id`
    FOREIGN KEY (`album_artist_id`)
    REFERENCES `Spotify`.`ARTIST` (`artist_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `album_record_company_id`
    FOREIGN KEY (`album_record_company_id`)
    REFERENCES `Spotify`.`RECORD_COMPANY` (`record_company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`SONGS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`SONGS` (
  `song_id` INT NOT NULL,
  `song_title` VARCHAR(45) NOT NULL,
  `song_duration` VARCHAR(45) NOT NULL,
  `song_play_counter` INT NOT NULL,
  `song_likes` INT NOT NULL,
  `song_album_id` INT NOT NULL,
  PRIMARY KEY (`song_id`),
  INDEX `song_album_id_idx` (`song_album_id` ASC) VISIBLE,
  CONSTRAINT `fk_song_album_id`
    FOREIGN KEY (`song_album_id`)
    REFERENCES `Spotify`.`ALBUM` (`album_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`SONG_PLAYLIST`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`SONG_PLAYLIST` (
  `song_playlist_id` INT NOT NULL,
  `playlist_id` INT NOT NULL,
  `song_id` INT NOT NULL,
  PRIMARY KEY (`song_playlist_id`),
  INDEX `playlist_id_idx` (`playlist_id` ASC) VISIBLE,
  INDEX `song_id_idx` (`song_id` ASC) VISIBLE,
  CONSTRAINT `fk_playlist_id`
    FOREIGN KEY (`playlist_id`)
    REFERENCES `Spotify`.`PLAYLISTS` (`playlist_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_song_id`
    FOREIGN KEY (`song_id`)
    REFERENCES `Spotify`.`SONGS` (`song_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`GENRE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`GENRE` (
  `genre_id` INT NOT NULL,
  `genre_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`genre_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`SONG_GENRE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`SONG_GENRE` (
  `song_genre_id` INT NOT NULL,
  `song_id` INT NOT NULL,
  `genre_id` INT NOT NULL,
  PRIMARY KEY (`song_genre_id`),
  INDEX `song_id_idx` (`song_id` ASC) VISIBLE,
  INDEX `genre_id_idx` (`genre_id` ASC) VISIBLE,
  CONSTRAINT `fk_song_id`
    FOREIGN KEY (`song_id`)
    REFERENCES `Spotify`.`SONGS` (`song_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_genre_id`
    FOREIGN KEY (`genre_id`)
    REFERENCES `Spotify`.`GENRE` (`genre_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '		';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
